### ISSUE TITLE
Can not load schema from sources ... UBL-Invoice-2.1.xsd

### ISSUE THREAD

**Issue by homebeaver** [itplr-kosit/xrechnung-schematron#24]
Hallo - ich spare mir das englische:

- ich habe von https://www.xoev.de/de/xrechnung das ganze bundle `xrechnung-1.2.0-bundle-2018-12-20.zip` zum Test rutergeladen
- und `validationtool-dist-1.0.1-standalone.zip` in ein Verz. entpackt
- meine Umgebung: nicht *nix, sondern win10 mit java 8

- und folgenden Test gemacht (hier mit para -dump):

```
 C:\proj\zugferd\xrechnung>java -jar validationtool-1.0.1-standalone.jar -s scenarios.xml -d -p -h 01.01a-INVOICE_ubl.xml
[main] INFO de.kosit.validationtool.api.CheckConfiguration - Creating default scenario repository (alongside scenario definition)
[main] INFO de.kosit.validationtool.impl.ScenarioRepository - Loading scenarios from file:///C:/proj/zugferd/xrechnung/scenarios.xml
[main] INFO de.kosit.validationtool.impl.ContentRepository - Load schema from source file:/C:/proj/zugferd/xrechnung/validationtool-1.0.1-standalone.jar!/xsd/scenarios.xsd
[main] INFO de.kosit.validationtool.impl.ScenarioRepository - Loaded scenarios for Prüftool-Konfiguration XRechnung 1.2.0 by KoSIT from 2018-12-19. The following scenarios are available:

EN16931 CIUS XRechnung (UBL Invoice)
EN16931 CIUS XRechnung (UBL CreditNote)
EN16931 CIUS XRechnung (CII)

[main] INFO de.kosit.validationtool.impl.ScenarioRepository - Loading scenario content from file:/C:/proj/zugferd/xrechnung/
[main] ERROR de.kosit.validationtool.cmd.CommandLineApplication - Can not load schema from sources file:/C:/proj/zugferd/xrechnung/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd
java.lang.IllegalArgumentException: Can not load schema from sources file:/C:/proj/zugferd/xrechnung/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd
        at de.kosit.validationtool.impl.ContentRepository.createSchema(ContentRepository.java:74)
        at de.kosit.validationtool.impl.ContentRepository.createSchema(ContentRepository.java:79)
        at de.kosit.validationtool.impl.ContentRepository.createSchema(ContentRepository.java:148)
        at de.kosit.validationtool.impl.model.BaseScenario.getSchema(BaseScenario.java:84)
        at de.kosit.validationtool.impl.model.BaseScenario.initialize(BaseScenario.java:99)
        at de.kosit.validationtool.impl.ScenarioRepository.lambda$initialize$0(ScenarioRepository.java:116)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at de.kosit.validationtool.impl.ScenarioRepository.initialize(ScenarioRepository.java:116)
        at de.kosit.validationtool.impl.DefaultCheck.<init>(DefaultCheck.java:76)
        at de.kosit.validationtool.cmd.InternalCheck.<init>(InternalCheck.java:48)
        at de.kosit.validationtool.cmd.CommandLineApplication.processActions(CommandLineApplication.java:135)
        at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:105)
        at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:85)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/proj/zugferd/xrechnung/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd; lineNumber: 35; columnNumber: 77; src-resolve: Name 'ext:UBLExtensions' kann nicht als 'element declaration'-Komponente aufgelöst werden.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4156)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4139)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1682)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseLocal(XSDElementTraverser.java:170)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseLocalElements(XSDHandler.java:3612)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:636)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:613)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:572)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:538)
        at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
        at de.kosit.validationtool.impl.ContentRepository.createSchema(ContentRepository.java:72)
        ... 12 more

```
- was mache ich falsch?
- ist es ein bug?
- ich habe mich noch nicht vertieft in die materie
- auch ja - und `UBL-Invoice-2.1.xsd` habe ich von `http://docs.oasis-open.org/ubl/os-UBL-2.1/xsd/maindoc/` rutergeladen müssen nach:

```
C:\proj\zugferd\xrechnung>dir resources\ubl\2.1\xsd\maindoc\UBL-Invoice-2.1.xsd
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: A740-67A9

 Verzeichnis von C:\proj\zugferd\xrechnung\resources\ubl\2.1\xsd\maindoc

11.04.2019  13:36            60.648 UBL-Invoice-2.1.xsd
               1 Datei(en),         60.648 Bytes
```

**Comment by homebeaver** [comment]
habe fehler gefunden: recources war nicht komplett

- und ausserdem ist das issue im falschen projekt `https://github.com/itplr-kosit/validator` wäre korrekt

regards
